// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import { client, healthCheck, login, serverInformation } from '../services.gen';
import type { LoginData, LoginError, LoginResponse } from '../types.gen';

type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const healthCheckQueryKey = (options?: Options) => [
    createQueryKey("healthCheck", options)
];

export const healthCheckOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await healthCheck({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckQueryKey(options)
}); };

export const loginQueryKey = (options: Options<LoginData>) => [
    createQueryKey("login", options)
];

export const loginOptions = (options: Options<LoginData>) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await login({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: loginQueryKey(options)
}); };

export const loginMutation = (options?: Partial<Options<LoginData>>) => { const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
    mutationFn: async (localOptions) => {
        const { data } = await login({
            ...options,
            ...localOptions,
            throwOnError: true
        });
        return data;
    }
}; return mutationOptions; };

export const serverInformationQueryKey = (options?: Options) => [
    createQueryKey("serverInformation", options)
];

export const serverInformationOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await serverInformation({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: serverInformationQueryKey(options)
}); };