[package]
name = "middlewares"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../../db/entity" }
utils = { path = "../../packages/utils" }
config = { path = "../config" }
actix-web = "4.9.0"
futures-util = "0.3.31"
sea-orm = { version = "1.1.0", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "debug-print",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"