// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  HealthCheckError,
  HealthCheckResponse,
  LoginData,
  LoginError,
  LoginResponse,
  ServerInformationError,
  ServerInformationResponse,
} from "./types.gen";

export const client = createClient(
  createConfig({
    baseUrl: "http://localhost:5003",
    credentials: "include"
  }),
);

export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponse,
    HealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/admin",
  });
};

/**
 * Login
 * Api to login for user
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginResponse,
    LoginError,
    ThrowOnError
  >({
    ...options,
    url: "/admin/auth/login",
  });
};

/**
 * Server Information
 */
export const serverInformation = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ServerInformationResponse,
    ServerInformationError,
    ThrowOnError
  >({
    ...options,
    url: "/admin/extra/server-information",
  });
};
