// This file is auto-generated by @hey-api/openapi-ts

export type AdminBadRequest = {
    message3: string;
    myName: string;
};

export type AdminInternalServerError = {
    hisName: string;
    message2: string;
};

export type AdminLoginInput = {
    fullName: string;
    password: string;
    username: string;
};

export type AdminLoginResponse = {
    message: string;
    username: string;
    yourName: string;
};

export type SystemInfo = {
    cpuUsage: number;
    freeMemory: number;
    lastCron: string;
    lastSuccessCron: string;
    osHostname: string;
    osPlatform: string;
    osVersion: string;
    totalMemory: number;
    upTime: number;
};

export type HealthCheckResponse = (string);

export type HealthCheckError = unknown;

export type LoginData = {
    body: AdminLoginInput;
};

export type LoginResponse = (AdminLoginResponse);

export type LoginError = (AdminBadRequest | AdminInternalServerError);

export type ServerInformationResponse = (SystemInfo);

export type ServerInformationError = unknown;