# Stage 1: Build
FROM node:18-alpine as builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

# Stage 2: Serve
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

RUN npm install --production

# Expose frontend port
EXPOSE 3000

CMD ["npm", "start"]
