// This file is auto-generated by @hey-api/openapi-ts

export type AdminLoginInput = {
    fullName: string;
    password: string;
    username: string;
};

export type AdminLoginResponse = {
    message: string;
    username: string;
    yourName: string;
};

export type AttributeModel = {
    createdAt: string;
    id: string;
    isActive: boolean;
    name: string;
    values: Array<AttributeValue>;
};

export type AttributeValue = {
    value: string;
};

export type Category = {
    category: string;
    id: string;
    title: string;
};

export type CreateAttributeInputDto = {
    /**
     * Name of the attribute.
     *
     */
    name: string;
    /**
     * Values of the attribute.
     */
    values: Array<AttributeValue>;
};

export type CreateAttributeResponseDto = {
    data: AttributeModel;
    message: string;
};

export type CreateCategoryInput = {
    /**
     * Title of the category.
     *
     */
    title: string;
};

export type CreateProductInput = {
    /**
     * Title of the product.
     *
     */
    title: string;
};

export type Product = {
    id: string;
    slug: string;
    title: string;
};

export type ResponseWithMessage = {
    message: string;
};

export type SystemInfo = {
    cpuUsage: number;
    freeMemory: number;
    lastCron: string;
    lastSuccessCron: string;
    osHostname: string;
    osPlatform: string;
    osVersion: string;
    totalMemory: number;
    upTime: number;
};

export type UpdateAttributeResponseDto = {
    data: AttributeModel;
    message: string;
};

export type UpdateAttributeStatusInputDto = {
    /**
     * Desired state of attribute.
     */
    isActive: boolean;
};

export type HealthCheckResponse = (string);

export type HealthCheckError = unknown;

export type LoginData = {
    body: AdminLoginInput;
};

export type LoginResponse = (AdminLoginResponse);

export type LoginError = (ResponseWithMessage);

export type ServerInformationResponse = (SystemInfo);

export type ServerInformationError = unknown;

export type GetAttributesResponse = (Array<AttributeModel>);

export type GetAttributesError = unknown;

export type CreateAttributeData = {
    body: CreateAttributeInputDto;
};

export type CreateAttributeResponse = (CreateAttributeResponseDto);

export type CreateAttributeError = unknown;

export type GetAttributeData = {
    path: {
        /**
         * Attribute Id
         */
        id: string;
    };
};

export type GetAttributeResponse = (AttributeModel);

export type GetAttributeError = unknown;

export type DeleteAttributeData = {
    path: {
        /**
         * Attribute Id
         */
        id: string;
    };
};

export type DeleteAttributeResponse = (ResponseWithMessage);

export type DeleteAttributeError = unknown;

export type UpdateAttributeData = {
    path: {
        /**
         * Attribute Id
         */
        id: string;
    };
};

export type UpdateAttributeResponse = (UpdateAttributeResponseDto);

export type UpdateAttributeError = unknown;

export type UpdateAttributeStatusData = {
    body: UpdateAttributeStatusInputDto;
    path: {
        /**
         * Attribute Id
         */
        id: string;
    };
};

export type UpdateAttributeStatusResponse = (UpdateAttributeResponseDto);

export type UpdateAttributeStatusError = unknown;

export type GetCategoriesResponse = (Array<Category>);

export type GetCategoriesError = unknown;

export type CreateCategoryData = {
    body: CreateCategoryInput;
};

export type CreateCategoryResponse = (Category);

export type CreateCategoryError = unknown;

export type GetCategoryData = {
    path: {
        /**
         * Category Id
         */
        id: string;
    };
};

export type GetCategoryResponse = (Category);

export type GetCategoryError = unknown;

export type DeleteCategoryData = {
    path: {
        /**
         * Category Id
         */
        id: string;
    };
};

export type DeleteCategoryResponse = (ResponseWithMessage);

export type DeleteCategoryError = unknown;

export type UpdateCategoryData = {
    path: {
        /**
         * Category Id
         */
        id: string;
    };
};

export type UpdateCategoryResponse = (Category);

export type UpdateCategoryError = unknown;

export type GetProductsResponse = (Product);

export type GetProductsError = unknown;

export type CreateProductData = {
    body: CreateProductInput;
};

export type CreateProductResponse = (Product);

export type CreateProductError = unknown;

export type GetProductData = {
    path: {
        /**
         * Product Id
         */
        id: string;
    };
};

export type GetProductResponse = (Product);

export type GetProductError = unknown;

export type DeleteProductData = {
    path: {
        /**
         * Product Id
         */
        id: string;
    };
};

export type DeleteProductResponse = (ResponseWithMessage);

export type DeleteProductError = unknown;

export type UpdateProductData = {
    path: {
        /**
         * Product Id
         */
        id: string;
    };
};

export type UpdateProductResponse = (Product);

export type UpdateProductError = unknown;