//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::address::Entity as Address;
pub use super::login_session::Entity as LoginSession;
pub use super::otp::Entity as Otp;
pub use super::user::Entity as User;
