//  This script is to fix default client generated by @hey-api/openapi-ts

import { readFileSync, writeFileSync } from "fs";
import path from "path";

async function main() {
  console.log("fixing..");
  const target = process.argv[2];
  if (target !== "www" && target !== "admin") {
    console.log("target must be 'www' or 'admin'");
    process.exit(1);
  }
  const sourcePath = path.resolve(
    __dirname,
    `../apps/${target}/src/client/services.gen.ts`
  );
  const data = readFileSync(sourcePath, "utf8");
  const lines = data.split("\n");
  const newLines = lines.map((line) => {
    if (line.includes("export const client")) {
      return `import { client } from "../utils/client" `;
    }
    return line;
  });
  writeFileSync(sourcePath, newLines.join("\n"));
  console.log("fix succeeded");
}
main();
