// This file is auto-generated by @hey-api/openapi-ts

export type AdminBadRequest = {
    message3: string;
    myName: string;
};

export type AdminInternalServerError = {
    hisName: string;
    message2: string;
};

export type AdminLoginInput = {
    fullName: string;
    password: string;
    username: string;
};

export type AdminLoginResponse = {
    message: string;
    username: string;
    yourName: string;
};

export type AuthForgotPassword = {
    /**
     * Email address of the user.
     */
    email: string;
};

/**
 * Credentials of the user.
 */
export type AuthLogin = {
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Password of the user.
     */
    password: string;
};

export type AuthRegister = {
    /**
     * Password Confirmation.
     */
    confirmPassword: string;
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Full name of the user.
     */
    fullName: string;
    /**
     * Password of the user.
     * Min. 8 characters.
     */
    password: string;
};

export type AuthRegisterVerify = AuthRegister & {
    /**
     * Verification code (OTP).
     */
    code: number;
};

export type AuthResetPassword = {
    /**
     * Password Confirmation.
     */
    confirmPassword: string;
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Verification code (OTP).
     */
    otp: number;
    /**
     * New Password to set.
     */
    password: string;
};

export type ResponseWithMessage = {
    message: string;
};

export type UpdateProfile = {
    full_name: string;
};

export type HealthCheckResponse = (string);

export type HealthCheckError = unknown;

export type AdminLoginData = {
    body: AdminLoginInput;
};

export type AdminLoginResponse2 = (AdminLoginResponse);

export type AdminLoginError = (AdminBadRequest | AdminInternalServerError);

export type ForgotPasswordData = {
    body: AuthForgotPassword;
};

export type ForgotPasswordResponse = (ResponseWithMessage);

export type ForgotPasswordError = (ResponseWithMessage);

export type LoginData = {
    body: AuthLogin;
};

export type LoginResponse = (ResponseWithMessage);

export type LoginError = (ResponseWithMessage);

export type LogoutResponse = (ResponseWithMessage);

export type LogoutError = (ResponseWithMessage);

export type RegisterData = {
    body: AuthRegister;
};

export type RegisterResponse = (ResponseWithMessage);

export type RegisterError = (ResponseWithMessage);

export type RegisterVerifyData = {
    body: AuthRegisterVerify;
};

export type RegisterVerifyResponse = (ResponseWithMessage);

export type RegisterVerifyError = (ResponseWithMessage);

export type ResetPasswordData = {
    body: AuthResetPassword;
};

export type ResetPasswordResponse = (ResponseWithMessage);

export type ResetPasswordError = (ResponseWithMessage);

export type UpdateProfileData = {
    body: UpdateProfile;
};

export type UpdateProfileResponse = (string);

export type UpdateProfileError = unknown;