// This file is auto-generated by @hey-api/openapi-ts

export type AdminBadRequest = {
    message3: string;
    myName: string;
};

export type AdminInternalServerError = {
    hisName: string;
    message2: string;
};

export type AdminLoginInput = {
    fullName: string;
    password: string;
    username: string;
};

export type AdminLoginResponse = {
    message: string;
    username: string;
    yourName: string;
};

export type AuthForgotPasswordInput = {
    /**
     * Email address of the user.
     */
    email: string;
};

/**
 * Credentials of the user.
 */
export type AuthLoginInput = {
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Password of the user.
     */
    password: string;
};

export type AuthRegisterInput = {
    /**
     * Password Confirmation.
     */
    confirmPassword: string;
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Full name of the user.
     */
    fullName: string;
    /**
     * Password of the user.
     * Min. 8 characters.
     */
    password: string;
};

export type AuthRegisterVerifyInput = AuthRegisterInput & {
    /**
     * Verification code (OTP).
     */
    code: number;
};

export type AuthResetPasswordInput = {
    /**
     * Password Confirmation.
     */
    confirmPassword: string;
    /**
     * Email address of the user.
     */
    email: string;
    /**
     * Verification code (OTP).
     */
    otp: number;
    /**
     * New Password to set.
     */
    password: string;
};

export type ResponseWithMessage = {
    message: string;
};

export type UpdateProfile = {
    full_name: string;
};

export type UserProfile = {
    createdAt: string;
    email: string;
    fullName: string;
    id: string;
    role: UserRole;
    status: UserStatus;
    updatedAt: string;
};

export type UserRole = 'Admin' | 'User';

export type UserStatus = 'Active' | 'Blocked';

export type HealthCheckResponse = (string);

export type HealthCheckError = unknown;

export type AdminLoginData = {
    body: AdminLoginInput;
};

export type AdminLoginResponse2 = (AdminLoginResponse);

export type AdminLoginError = (AdminBadRequest | AdminInternalServerError);

export type ForgotPasswordData = {
    body: AuthForgotPasswordInput;
};

export type ForgotPasswordResponse = (ResponseWithMessage);

export type ForgotPasswordError = (ResponseWithMessage);

export type LoginData = {
    body: AuthLoginInput;
};

export type LoginResponse = (ResponseWithMessage);

export type LoginError = (ResponseWithMessage);

export type LogoutResponse = (ResponseWithMessage);

export type LogoutError = (ResponseWithMessage);

export type RegisterData = {
    body: AuthRegisterInput;
};

export type RegisterResponse = (ResponseWithMessage);

export type RegisterError = (ResponseWithMessage);

export type RegisterVerifyData = {
    body: AuthRegisterVerifyInput;
};

export type RegisterVerifyResponse = (ResponseWithMessage);

export type RegisterVerifyError = (ResponseWithMessage);

export type ResetPasswordData = {
    body: AuthResetPasswordInput;
};

export type ResetPasswordResponse = (ResponseWithMessage);

export type ResetPasswordError = (ResponseWithMessage);

export type UpdateProfileData = {
    body: UpdateProfile;
};

export type UpdateProfileResponse = (string);

export type UpdateProfileError = unknown;

export type GetUserResponse = (UserProfile);

export type GetUserError = unknown;