[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
sea-orm = { version = "1.1.0", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "debug-print",
] }
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
utoipa = { version = "5.1.1", features = ["actix_extras", "chrono"] }
thiserror = "1.0.64"
argon2 = "0.5.3"
chrono = { version = "0.4.38", features = ["serde"] }
rand = "0.8.5"
jsonwebtoken = "9.3.0"